### ISSUE TITLE
creating real subviews?

### ISSUE THREAD

**Issue by exocode** [DingHub/SwipeableCards#1]
I have a question:

your are "building the view by coding" (viewFor - method).

Is it also possible to place the labels and images in a xib, so I can make more a WYSIWYG experience?

I am (relatively) new to swift, but this issue is taking now two days of trial and error. Maybe you can help me out:

<img width="651" alt="bildschirmfoto 2016-09-17 um 10 51 37" src="https://cloud.githubusercontent.com/assets/1597621/18607154/c10ad13e-7cc4-11e6-93e0-f8d4c474e26b.png">

many thanks in advance

**Comment by zrcoder** [comment]
You can create a custom view using xib and use it in data source method :view(for...).
Can't register the nib like UITableViewCell . Maybe, we will support in future.
