### ISSUE TITLE
[!] Unable to find a specification for 'SwipeableCards'.

### ISSUE THREAD

**Issue by Jamongkad** [DingHub/SwipeableCards#2]
Hi! I'm unable to check out the Swift3 branch. Here's my what's on my Podfile...

pod 'SwipeableCards', :git => 'https://github.com/DingHub/SwipeableCards.git', :branch => 'Swift3'

**Comment by zrcoder** [comment]
Ah~ I deleted the swift3 branch in fact.
The latest version is written in Swift3.
